import Head from 'next/head';
import styles from '../styles/Home.module.css';
import factory from '../ethereum/factory';
import { useEffect, useState } from 'react';
import { Card, Button } from 'semantic-ui-react';
import Layout from '../components/Layout';
import Link from "next/link";

export default function Home({ contractMap }) {
  const [contracts, setContracts] = useState([{}]);

  useEffect(() => {
    getContracts();
  }, []);

  const getContracts = async () => {
    const contractList = await factory.methods.getDeployedCampaigns().call();
    setContracts(contractList);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Link href={'/campaigns/new'}>
          <Button
            floated="right"
            icon="add circle"
            content="Create Campaign"
            primary
          />
        </Link>
        <h3>Open Campaigns</h3>
        {contractMap.map((contract, i) => {
          return (
            <Card.Group key={i}>
              <Card fluid={true}>
                <Card.Content>
                  <Card.Header>{contract.header}</Card.Header>
                  <Card.Description>
                    <Link href={`/campaigns/${contract.header}`}><a>View Campaign</a></Link>
                  </Card.Description>
                </Card.Content>
              </Card>
            </Card.Group>
          );
        })}
      </Layout>
    </div>
  );
}

Home.getInitialProps = async (ctx) => {
  const contractList = await factory.methods.getDeployedCampaigns().call();

  const contractMap = contractList.map((address) => {
    return {
      header: address,
    };
  });

  return { contractMap };
};
